// requests.jsonl (from `mix r1.requests` in r1-spike/harness) -> requests.gen.ts, which the app bundles.
// Base64 keeps the raw bytes, including the deliberately invalid UTF-8 lines.
// scale-2.jsonl (`mix r1.scale`, version r1-scale-2; touched-1 rerun) -> scale.gen.ts: one string per line (ASCII JSON).
// scale.jsonl (r1-scale-1, the stateless run's input) is retained unchanged and no longer bundled.
import { readFileSync, writeFileSync } from 'node:fs';

const dir = new URL('..', import.meta.url);
const b64 = readFileSync(new URL('requests.jsonl', dir)).toString('base64');
writeFileSync(new URL('requests.gen.ts', dir), `// Generated by scripts/embed.mjs from requests.jsonl. Do not edit.\nexport default '${b64}';\n`);
const scale = readFileSync(new URL('scale-2.jsonl', dir), 'utf8').trim().split('\n');
writeFileSync(new URL('scale.gen.ts', dir), `// Generated by scripts/embed.mjs from scale-2.jsonl. Do not edit.\nexport default ${JSON.stringify(scale)} as string[];\n`);
