// requests.jsonl (from `mix r1.requests` in r1-spike/harness) -> requests.gen.ts, which the app bundles.
// Base64 keeps the raw bytes, including the deliberately invalid UTF-8 lines.
import { readFileSync, writeFileSync } from 'node:fs';

const dir = new URL('..', import.meta.url);
const b64 = readFileSync(new URL('requests.jsonl', dir)).toString('base64');
writeFileSync(new URL('requests.gen.ts', dir), `// Generated by scripts/embed.mjs from requests.jsonl. Do not edit.\nexport default '${b64}';\n`);
